"use client";

import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import {
    AlertTriangle,
    CheckCircle2,
    Sparkles,
    TrendingUp
} from "lucide-react";

interface AIAnalysisProps {
  analysis: {
    growth_score: number;
    risk_score: number;
    executive_summary: string;
    automation_potential: string;
    growth_opportunities: string[];
  } | null;
  quickTake?: string;
}

export default function AIAnalysisSection({ analysis, quickTake }: AIAnalysisProps) {
  if (!analysis) return null;

  return (
    <section className="space-y-6">
      <div className="flex items-center gap-4 mb-2">
        <h2 className="text-xl font-bold flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-blue-500" /> AI Deal Intelligence
        </h2>
        <Badge variant="secondary" className="bg-blue-100 text-blue-700 border-blue-200">
          Generated by NxtOwner AI
        </Badge>
        {quickTake && (
          <Badge variant="outline" className="bg-yellow-50 text-yellow-800 border-yellow-200">
            Quick Take: {quickTake}
          </Badge>
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Growth Score */}
        <Card className="flex flex-col items-center p-6 gap-3">
          <span className="font-semibold flex items-center gap-2 text-blue-700">
            <TrendingUp className="w-5 h-5" /> Growth Score
          </span>
          <CircularGauge value={analysis.growth_score} color="#2563eb" />
          <span className="text-lg font-bold text-blue-700">{analysis.growth_score}/100</span>
        </Card>

        {/* Risk Score */}
        <Card className="flex flex-col items-center p-6 gap-3">
          <span className="font-semibold flex items-center gap-2 text-orange-600">
            <AlertTriangle className="w-5 h-5" /> Risk Score
          </span>
          <CircularGauge value={analysis.risk_score} color="#ef4444" />
          <span className="text-lg font-bold text-orange-600">{analysis.risk_score}/100</span>
        </Card>
      </div>

      <Card className="p-6">
        <h3 className="font-semibold mb-2 text-gray-800">Executive Summary</h3>
        <p className="text-gray-700 whitespace-pre-line">{analysis.executive_summary}</p>
      </Card>

      <Card className="p-6 bg-blue-50 border-blue-100">
        <h3 className="font-semibold mb-2 text-blue-800 flex items-center gap-2">
          <CheckCircle2 className="w-5 h-5 text-blue-500" /> Automation Strategy
        </h3>
        <p className="text-blue-700 whitespace-pre-line">{analysis.automation_potential}</p>
      </Card>

      {analysis.growth_opportunities?.length > 0 && (
        <Card className="p-6">
          <h3 className="font-semibold mb-2 text-green-800 flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-green-500" /> Growth Opportunities
          </h3>
          <ul className="list-disc pl-6 space-y-1">
            {analysis.growth_opportunities.map((item, i) => (
              <li key={i} className="text-green-700">{item}</li>
            ))}
          </ul>
        </Card>
      )}
    </section>
  );
}

// Internal Gauge Component
function CircularGauge({ value, color }: { value: number; color: string }) {
  const radius = 36;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (value / 100) * circumference;

  return (
    <svg className="w-24 h-24 transform -rotate-90">
      <circle
        cx="48"
        cy="48"
        r={radius}
        stroke="currentColor"
        strokeWidth="8"
        fill="transparent"
        className="text-gray-100"
      />
      <circle
        cx="48"
        cy="48"
        r={radius}
        stroke={color}
        strokeWidth="8"
        strokeDasharray={circumference}
        style={{ strokeDashoffset: offset }}
        strokeLinecap="round"
        fill="transparent"
      />
    </svg>
  );
}