export type Json = string | number | boolean | null | { [key: string]: Json } | Json[];

export type Database = {
  public: {
    Tables: {
      listings: {
        Row: {
          id: string | null;
          owner_id: string | null;
          created_at: string | null;
          updated_at: string | null;
          status: string | null;
          deal_stage: string | null;
          asset_type: string | null;
          category_id: string | null;
          subcategory_id: string | null;
          category: string | null;
          subcategory: string | null;
          title: string | null;
          hero_image_url: string | null;
          country: string | null;
          province: string | null;
          city: string | null;
          postal_code: string | null;
          is_remote: boolean | null;
          asking_price: number | null;
          currency: string | null;
          deal_structure: string | null;
          business_status: string | null;
          confidentiality_level: string | null;
          verification_level: string | null;
          listing_tier: string | null;
          visibility_boost: boolean | null;
          revenue_annual: number | null;
          ebitda_annual: number | null;
          cash_flow_annual: number | null;
          noi_annual: number | null;
          revenue_growth_pct: number | null;
          revenue_trend: string | null;
          sde: number | null;
          noi: number | null;
          ebitda: number | null;
          cash_flow: number | null;
          gross_revenue: number | null;
          gross_margin_pct: number | null;
          net_margin_pct: number | null;
          asking_multiple_ebitda: number | null;
          asking_multiple_sde: number | null;
          asking_multiple_revenue: number | null;
          cap_rate_pct: number | null;
          inventory_included: boolean | null;
          inventory_value: number | null;
          equipment_value: number | null;
          real_estate_included: boolean | null;
          real_estate_value: number | null;
          has_existing_debt: boolean | null;
          debt_balance: number | null;
          has_liens: boolean | null;
          offers_vtb: boolean | null;
          seller_financing_pct: number | null;
          offers_earnout: boolean | null;
          offers_lease_to_own: boolean | null;
          assumable_loans: boolean | null;
          views_count: number | null;
          saves_count: number | null;
          nda_requests_count: number | null;
          loi_interest_count: number | null;
          last_activity_at: string | null;
          meta_operational: Record<string, any> | null;
          meta_digital: Record<string, any> | null;
          ai: Record<string, any> | null;
          ai_growth_score: number | null;
          ai_risk_score: number | null;
          ai_summary: string | null;
        };
        Insert: {
          id?: string | null;
          owner_id?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          status?: string | null;
          deal_stage?: string | null;
          asset_type?: string | null;
          category_id?: string | null;
          subcategory_id?: string | null;
          category?: string | null;
          subcategory?: string | null;
          title?: string | null;
          hero_image_url?: string | null;
          country?: string | null;
          province?: string | null;
          city?: string | null;
          postal_code?: string | null;
          is_remote?: boolean | null;
          asking_price?: number | null;
          currency?: string | null;
          deal_structure?: string | null;
          business_status?: string | null;
          confidentiality_level?: string | null;
          verification_level?: string | null;
          listing_tier?: string | null;
          visibility_boost?: boolean | null;
          revenue_annual?: number | null;
          ebitda_annual?: number | null;
          cash_flow_annual?: number | null;
          noi_annual?: number | null;
          revenue_growth_pct?: number | null;
          revenue_trend?: string | null;
          sde?: number | null;
          noi?: number | null;
          ebitda?: number | null;
          cash_flow?: number | null;
          gross_revenue?: number | null;
          gross_margin_pct?: number | null;
          net_margin_pct?: number | null;
          asking_multiple_ebitda?: number | null;
          asking_multiple_sde?: number | null;
          asking_multiple_revenue?: number | null;
          cap_rate_pct?: number | null;
          inventory_included?: boolean | null;
          inventory_value?: number | null;
          equipment_value?: number | null;
          real_estate_included?: boolean | null;
          real_estate_value?: number | null;
          has_existing_debt?: boolean | null;
          debt_balance?: number | null;
          has_liens?: boolean | null;
          offers_vtb?: boolean | null;
          seller_financing_pct?: number | null;
          offers_earnout?: boolean | null;
          offers_lease_to_own?: boolean | null;
          assumable_loans?: boolean | null;
          views_count?: number | null;
          saves_count?: number | null;
          nda_requests_count?: number | null;
          loi_interest_count?: number | null;
          last_activity_at?: string | null;
          meta_operational?: Record<string, any> | null;
          meta_digital?: Record<string, any> | null;
          ai?: Record<string, any> | null;
          ai_growth_score?: number | null;
          ai_risk_score?: number | null;
          ai_summary?: string | null;
        };
        Update: {
          id?: string | null;
          owner_id?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          status?: string | null;
          deal_stage?: string | null;
          asset_type?: string | null;
          category_id?: string | null;
          subcategory_id?: string | null;
          category?: string | null;
          subcategory?: string | null;
          title?: string | null;
          hero_image_url?: string | null;
          country?: string | null;
          province?: string | null;
          city?: string | null;
          postal_code?: string | null;
          is_remote?: boolean | null;
          asking_price?: number | null;
          currency?: string | null;
          deal_structure?: string | null;
          business_status?: string | null;
          confidentiality_level?: string | null;
          verification_level?: string | null;
          listing_tier?: string | null;
          visibility_boost?: boolean | null;
          revenue_annual?: number | null;
          ebitda_annual?: number | null;
          cash_flow_annual?: number | null;
          noi_annual?: number | null;
          revenue_growth_pct?: number | null;
          revenue_trend?: string | null;
          sde?: number | null;
          noi?: number | null;
          ebitda?: number | null;
          cash_flow?: number | null;
          gross_revenue?: number | null;
          gross_margin_pct?: number | null;
          net_margin_pct?: number | null;
          asking_multiple_ebitda?: number | null;
          asking_multiple_sde?: number | null;
          asking_multiple_revenue?: number | null;
          cap_rate_pct?: number | null;
          inventory_included?: boolean | null;
          inventory_value?: number | null;
          equipment_value?: number | null;
          real_estate_included?: boolean | null;
          real_estate_value?: number | null;
          has_existing_debt?: boolean | null;
          debt_balance?: number | null;
          has_liens?: boolean | null;
          offers_vtb?: boolean | null;
          seller_financing_pct?: number | null;
          offers_earnout?: boolean | null;
          offers_lease_to_own?: boolean | null;
          assumable_loans?: boolean | null;
          views_count?: number | null;
          saves_count?: number | null;
          nda_requests_count?: number | null;
          loi_interest_count?: number | null;
          last_activity_at?: string | null;
          meta_operational?: Record<string, any> | null;
          meta_digital?: Record<string, any> | null;
          ai?: Record<string, any> | null;
          ai_growth_score?: number | null;
          ai_risk_score?: number | null;
          ai_summary?: string | null;
        };
      };
      // keep your other table definitions here...
    };
  };
};
